# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170509_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkeli',
            name='otsikko',
            field=models.CharField(max_length=75),
        ),
    ]
