# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170510_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikkeli',
        ),
    ]
